version: "3"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: deployit_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - .local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - .pgadmin-data:/var/lib/pgadmin
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    restart: unless-stopped
    volumes:
      - .rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"

  deploy-it:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: 501
    hostname: deploy-it
    container_name: deploy-it
    restart: unless-stopped
    environment:
      PORT: 3000
      JWT_SECRET: R5BACzmjYf
      DB_DRIVER: postgres
      DB_USER: user
      DB_PASSWORD: admin
      DB_NAME: deployit_db
      DB_HOST: db
      DB_PORT: 5432
      DB_MIGRATE: false
      DB_LOG_ENABLED: true
      RABBIT_MQ_URL: amqp://guest:guest@rabbit-mq:5672
      RABBIT_MQ_DEPLOY_IT_EXCHANGE: deployIt_exchange
      RABBIT_MQ_DEPLOY_IT_JOB_ROUTING_KEY: deployit.jobs
      RABBIT_MQ_DEPLOY_IT_JOB_QUEUE: deployit_job_queue
      REPOSITORIES_LOCAL_DIR_PATH: /repositories
    depends_on:
      - db
      - rabbit-mq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"