version: "3"
services:
  deploy-it:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: deploy-it
    container_name: deploy-it
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${PORT}:${PORT}"